[package]
name = "ineed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpassword = { version = "7.3.1", optional = true }
thiserror = "1.0.57"

[dev-dependencies]
anyhow = "1.0.80"

[features]
default = []
rpassword = ["dep:rpassword"]
_nightly = []

[package.metadata.docs.rs]
all-features = true
